### ISSUE TITLE
timeSeries does not work

### ISSUE THREAD

**Issue by fcrisciani** [wagenaartje/stocks.js#8]
```
"use strict";
exports.__esModule = true;
var stocks = require("stocks.js");
stocks.API_KEY = 'XXXX';
stocks.timeSeries({
    symbol: 'TSLA',
    interval: '1min',
    amount: 10
}, function (err, res) {
    console.log(res);
});
```

Debugged a little bit and the URL created is messed up, the interval is rewritten
```
Processing Key:function = TIME_SERIES_intraday 
Processing Key:symbol = TSLA 
Processing Key:outputsize = full 
Processing Key:1min = undefined1min 
This is the URL: [https://www.alphavantage.co/query?apikey=Q7U8TQA8Q5ZBYYTY&function=TIME_SERIES_intraday&symbol=TSLA&outputsize=full&1min=undefined1min&]
```

Stacktrace if useful:
```
Error: An error occured. Please create an issue at https://github.com/wagenaartje/stocks/issues with your code, and provide the following message: Invalid API call, please visit doc
umentation (https://www.alphavantage.co/documentation/) for function: TIME_SERIES_INTRADAY                                                                                           
    at exports.XMLHttpRequest.request.onload (/app/node_modules/stocks.js/src/stocks.js:56:21)
    at exports.XMLHttpRequest.dispatchEvent (/app/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/app/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:614:14)                            
    at IncomingMessage.<anonymous> (/app/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:110:20)                                                                
    at IncomingMessage.emit (events.js:207:7)                                                                        
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)           
    at process._tickCallback (internal/process/next_tick.js:161:9) 
```

**Comment by wagenaartje** [comment]
Oops! Seems like a bug was introduced after a recent PR. Should be fixed now, let me know if anything is still wrong.

I'll introduce some build testing with `mocha` later, so bugs like this won't occur anymore :+1:
