### ISSUE TITLE
nodejs broken

### ISSUE THREAD

**Issue by fcrisciani** [wagenaartje/stocks.js#9]
I guess the commit of the global variable broke nodejs [https://github.com/wagenaartje/stocks.js/commit/8548d96010f2f48dbf7bc649bf27883dd07fbc01].

program:
```
var stocks = require("stocks.js");                                  
stocks.API_KEY = 'XXXX';                                            
stocks.timeSeries({                                                 
    symbol: 'TSLA',                                                 
    interval: '1min',                                               
    amount: 10                                                      
}, function (err, res) {                                            
    console.log(res);                                               
}); 
```

result:
```
stocks.timeSeries({
       ^

TypeError: stocks.timeSeries is not a function
    at Object.<anonymous> (/app/app3.js:3:8)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by wagenaartje** [comment]
Your 'program' code is incorrect, it should be something like:

```js
var Stocks = require("stocks.js");
var stocks = new Stocks('XXXX');       
                                                       
stocks.timeSeries({                                                 
    symbol: 'TSLA',                                                 
    interval: '1min',                                               
    amount: 10                                                      
}, function (err, res) {                                            
    console.log(res);                                               
}); 
```

See [Getting Started](https://github.com/wagenaartje/stocks.js#getting-started)!

**Comment by fcrisciani** [comment]
@wagenaartje sorry you are right, thanks!
